# -*- coding: utf-8 -*-
"""Streamlit_deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AxDTofyrEkJayXLLc5iMU-pvuKoXn1i8
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install git+https://github.com/ultralytics/ultralytics.git

from ultralytics import YOLO
model = YOLO('/content/drive/MyDrive/license_plate_detection.pt')

!pip install Streamlit
!git clone https://huggingface.co/spaces/Mike-Alem/Streamlit-LPD

import streamlit as st
import cv2
import numpy as np
from ultralytics import YOLO  # Or your preferred object detection library

# Load your pre-trained YOLOv8 model or any other model
model = YOLO('/content/drive/MyDrive/license_plate_detection.pt')

def process_image(image):
    """Detects license plates in an image and returns annotated image."""
    results = model.predict(image, conf=0.5)  # Adjust confidence as needed
    annotated_image = results[0].plot()  # Or your preferred annotation method
    return annotated_image

# Streamlit app
st.title("Automatic License Plate Detection")

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    # Read the uploaded image
    image = cv2.imdecode(np.fromstring(uploaded_file.read(), np.uint8), 1)

    # Process the image
    annotated_image = process_image(image)

    # Display the annotated image
import streamlit as st
import cv2
import numpy as np
from ultralytics import YOLO  # Or your preferred object detection library

# Load your pre-trained  model
try:
    model = YOLO('/content/drive/MyDrive/license_plate_detection.pt')
except Exception as e:
    st.error(f"Error loading model: {e}")
    st.stop()

def process_image(image):
    """Detects license plates in an image and returns annotated image."""
    results = model.predict(image, conf=0.5)  # Adjust confidence as needed
    annotated_image = results[0].plot()  # Or your preferred annotation method
    return annotated_image

# Streamlit app
st.title("Automatic License Plate Detection")

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "png", "jpeg"])

if uploaded_file is not None:
    # Read the uploaded image
    image = cv2.imdecode(np.fromstring(uploaded_file.read(), np.uint8), 1)

    # Process the image
    annotated_image = process_image(image)

    # Display the annotated image
    st.image(annotated_image, caption="Detected License Plates", use_column_width=True)
    st.write("License plate detection completed!")

!streamlit run /content/drive/MyDrive/Colab Notebooks/Deployment.ipynb